local M = {}

---@param colors ColorTable
---@return YorumiTheme
M.ether = function(colors)
  return {
    palette = colors,
    overrides = {},
    ui = {
      fg = colors.light_70,
      fg_dim = colors.light_60,
      fg_reverse = colors.blue_70,
      bg_dim = colors.dark_10,
      bg_gutter = colors.dark_40,
      fg_gutter = colors.light_40,
      fg_special = colors.purple_90,
      bg_special = colors.purple_20,
      bg_m3 = colors.dark_10,
      bg_m2 = colors.dark_20,
      bg_m1 = colors.dark_30,
      bg = colors.dark_20,
      bg_p1 = colors.dark_30,
      bg_p2 = colors.dark_40,
      special = colors.magenta_70,
      nontext = colors.dark_50,
      whitespace = colors.dark_50,
      bg_CurSearch = colors.blue_50,
      fg_CurSearch = colors.light_90,
      bg_search = colors.dark_50,
      fg_search = colors.light_70,
      bg_visual = colors.blue_70,
      fg_visual = colors.light_50,
      pmenu = {
        bg = colors.dark_30,
        fg = colors.light_70,
        bg_sel = colors.dark_40,
        fg_sel = colors.light_70,
        bg_sbar = colors.dark_30,
        bg_thumb = colors.dark_50,
      },
      float = {
        bg = colors.dark_10,
        fg = colors.light_70,
        fg_border = colors.light_60,
      },
    },
    syn = {
      string = colors.green_70,
      variable = "none",
      number = colors.red_70,
      constant = colors.orange_70,
      identifier = colors.yellow_70,
      parameter = colors.magenta_70,
      fun = colors.blue_70,
      statement = colors.magenta_70,
      keyword = colors.purple_80,
      operator = colors.yellow_70,
      preproc = colors.red_70,
      type = colors.cyan_70,
      regex = colors.red_70,
      deprecated = colors.dark_60,
      comment = colors.light_20,
      punct = colors.magenta_70,
      special1 = colors.blue_70,
      special2 = colors.red_70,
      special3 = colors.orange_70,
    },
    diag = {
      error = colors.red_70,
      error_bg = colors.red_20,
      ok = colors.green_70,
      warning = colors.yellow_70,
      info = colors.blue_70,
      hint = colors.cyan_70,
    },
    diff = {
      add = colors.green_70,
      delete = colors.red_70,
      change = colors.blue_70,
      text = colors.yellow_70,
    },
    vcs = {
      added = colors.green_70,
      removed = colors.red_70,
      changed = colors.yellow_70,
    },
    term = {
      colors.dark_20,
      colors.red_70,
      colors.green_70,
      colors.yellow_70,
      colors.blue_70,
      colors.magenta_70,
      colors.cyan_70,
      colors.light_70,
      colors.dark_40,
      colors.red_90,
      colors.green_90,
      colors.yellow_90,
      colors.blue_90,
      colors.magenta_90,
      colors.cyan_90,
      colors.light_90,
    },
  }
end

---@param colors ColorTable
---@return YorumiTheme
M.abyss = function(colors)
  return {
    palette = colors,
    overrides = {
    },
    ui = {
      fg = colors.light_50,
      fg_dim = colors.light_40,
      fg_reverse = colors.blue_70,
      bg_dim = colors.dark_20,
      bg_gutter = colors.dark_30,
      fg_gutter = colors.dark_50,
      fg_special = colors.magenta_90,
      bg_special = colors.magenta_20,
      bg_m3 = colors.dark_10,
      bg_m2 = colors.dark_20,
      bg_m1 = colors.dark_30,
      bg = colors.dark_30,
      bg_p1 = colors.dark_40,
      bg_p2 = colors.dark_50,
      special = colors.magenta_90,
      nontext = colors.dark_90,
      whitespace = colors.dark_40,
      bg_CurSearch = colors.blue_50,
      fg_CurSearch = colors.light_90,
      bg_search = colors.dark_50,
      fg_search = colors.light_50,
      bg_visual = colors.blue_30,
      fg_visual = colors.light_50,
      pmenu = {
        bg = colors.dark_50,
        fg = colors.light_50,
        bg_sel = colors.blue_90,
        fg_sel = colors.dark_20,
        bg_sbar = colors.dark_40,
        bg_thumb = colors.dark_60,
      },
      float = {
        bg = colors.dark_20,
        fg = colors.light_50,
        fg_border = colors.light_40,
      },
    },
    syn = {
      string = colors.green_80,
      variable = "none",
      number = colors.red_80,
      constant = colors.orange_80,
      identifier = colors.yellow_80,
      parameter = colors.magenta_80,
      fun = colors.blue_80,
      statement = colors.magenta_70,
      keyword = colors.purple_80,
      operator = colors.yellow_80,
      preproc = colors.red_80,
      type = colors.cyan_80,
      regex = colors.red_80,
      deprecated = colors.dark_80,
      comment = colors.dark_90,
      punct = colors.light_30,
      special1 = colors.blue_80,
      special2 = colors.red_80,
      special3 = colors.orange_80,
    },
    diag = {
      error = colors.red_80,
      error_bg = colors.red_20,
      ok = colors.green_80,
      warning = colors.yellow_80,
      info = colors.blue_80,
      hint = colors.cyan_80,
    },
    diff = {
      add = colors.green_20,
      delete = colors.red_20,
      change = colors.blue_20,
      text = colors.yellow_20,
    },
    vcs = {
      added = colors.green_80,
      removed = colors.red_80,
      changed = colors.yellow_80,
    },
    term = {
      colors.dark_30,
      colors.red_80,
      colors.green_80,
      colors.yellow_80,
      colors.blue_80,
      colors.magenta_80,
      colors.cyan_80,
      colors.light_50,
      colors.dark_50,
      colors.red_90,
      colors.green_90,
      colors.yellow_90,
      colors.blue_90,
      colors.magenta_90,
      colors.cyan_90,
      colors.light_70,
    },
  }
end

---@param colors ColorTable
---@return YorumiTheme
M.bifrost = function(colors)
  return {
    palette = colors,
    overrides = {},
    ui = {
      fg = colors.dark_20,
      fg_dim = colors.dark_30,
      fg_reverse = colors.blue_60,
      bg_dim = colors.light_80,
      bg_gutter = colors.light_60,
      fg_gutter = colors.dark_50,
      fg_special = colors.purple_60,
      bg_special = colors.purple_90,
      bg_m3 = colors.light_100,
      bg_m2 = colors.light_90,
      bg_m1 = colors.light_80,
      bg = colors.light_90,
      bg_p1 = colors.light_80,
      bg_p2 = colors.light_70,
      special = colors.purple_60,
      nontext = colors.light_50,
      whitespace = colors.light_50,
      bg_CurSearch = colors.yellow_40,
      fg_CurSearch = colors.dark_30,
      bg_search = colors.dark_50,
      fg_search = colors.dark_50,
      bg_visual = colors.blue_60,
      fg_visual = colors.dark_60,
      pmenu = {
        bg = colors.light_80,
        fg = colors.dark_20,
        bg_sel = colors.light_70,
        fg_sel = colors.dark_20,
        bg_sbar = colors.light_80,
        bg_thumb = colors.light_60,
      },
      float = {
        bg = colors.light_100,
        fg = colors.dark_20,
        fg_border = colors.light_80,
      },
    },
    syn = {
      string = colors.green_60,
      variable = "none",
      number = colors.red_60,
      constant = colors.orange_60,
      identifier = colors.yellow_60,
      parameter = colors.magenta_60,
      fun = colors.blue_60,
      statement = colors.magenta_60,
      keyword = colors.purple_70,
      operator = colors.yellow_60,
      preproc = colors.red_60,
      type = colors.cyan_60,
      regex = colors.red_70,
      deprecated = colors.light_30,
      comment = colors.dark_40,
      punct = colors.purple_60,
      special1 = colors.blue_60,
      special2 = colors.red_60,
      special3 = colors.orange_60,
    },
    diag = {
      error = colors.red_60,
      error_bg = colors.red_10,
      ok = colors.green_60,
      warning = colors.yellow_60,
      info = colors.blue_60,
      hint = colors.cyan_60,
    },
    diff = {
      add = colors.green_60,
      delete = colors.red_60,
      change = colors.blue_60,
      text = colors.yellow_60,
    },
    vcs = {
      added = colors.green_60,
      removed = colors.red_60,
      changed = colors.yellow_60,
    },
    term = {
      colors.dark_20,
      colors.red_60,
      colors.green_60,
      colors.yellow_60,
      colors.blue_60,
      colors.magenta_60,
      colors.cyan_60,
      colors.light_10,
      colors.dark_90,
      colors.red_70,
      colors.green_70,
      colors.yellow_70,
      colors.blue_70,
      colors.magenta_70,
      colors.cyan_70,
      colors.light_40,
    },
  }
end

---@param colors ColorTable
---@return YorumiTheme
M.mist = function(colors)
  return {
    palette = colors,
    overrides = {},
    ui = {
      fg = colors.dark_30,
      fg_dim = colors.dark_40,
      fg_reverse = colors.blue_40,
      bg_dim = colors.light_70,
      bg_gutter = colors.light_50,
      fg_gutter = colors.dark_40,
      fg_special = colors.purple_40,
      bg_special = colors.purple_80,
      bg_m3 = colors.light_100,
      bg_m2 = colors.light_80,
      bg_m1 = colors.light_60,
      bg = colors.light_50,
      bg_p1 = colors.light_60,
      bg_p2 = colors.light_70,
      special = colors.purple_40,
      nontext = colors.light_40,
      whitespace = colors.light_40,
      bg_CurSearch = colors.blue_40,
      fg_CurSearch = colors.dark_30,
      bg_search = colors.dark_40,
      fg_search = colors.dark_40,
      bg_visual = colors.blue_40,
      fg_visual = colors.dark_40,
      pmenu = {
        bg = colors.light_60,
        fg = colors.dark_30,
        bg_sel = colors.light_70,
        fg_sel = colors.dark_30,
        bg_sbar = colors.light_60,
        bg_thumb = colors.light_50,
      },
      float = {
        bg = colors.light_100,
        fg = colors.dark_30,
        fg_border = colors.light_70,
      },
    },
    syn = {
      string = colors.green_40,
      variable = "none",
      number = colors.red_40,
      constant = colors.orange_40,
      identifier = colors.yellow_40,
      parameter = colors.magenta_40,
      fun = colors.blue_40,
      statement = colors.magenta_40,
      keyword = colors.purple_50,
      operator = colors.yellow_40,
      preproc = colors.red_40,
      type = colors.cyan_40,
      regex = colors.red_50,
      deprecated = colors.light_20,
      comment = colors.dark_50,
      punct = colors.purple_40,
      special1 = colors.blue_40,
      special2 = colors.red_40,
      special3 = colors.orange_40,
    },
    diag = {
      error = colors.red_40,
      error_bg = colors.red_10,
      ok = colors.green_40,
      warning = colors.yellow_40,
      info = colors.blue_40,
      hint = colors.cyan_40,
    },
    diff = {
      add = colors.green_40,
      delete = colors.red_40,
      change = colors.blue_40,
      text = colors.yellow_40,
    },
    vcs = {
      added = colors.green_40,
      removed = colors.red_40,
      changed = colors.yellow_40,
    },
    term = {
      colors.dark_30,
      colors.red_40,
      colors.green_40,
      colors.yellow_40,
      colors.blue_40,
      colors.magenta_40,
      colors.cyan_40,
      colors.light_50,
      colors.dark_80,
      colors.red_60,
      colors.green_60,
      colors.yellow_60,
      colors.blue_60,
      colors.magenta_60,
      colors.cyan_60,
      colors.light_90,
    },
  }
end

---@param theme string
---@return YorumiTheme
M.get_theme = function(theme)
  local colors = require("yorumi.colors")()
  return M[theme](colors)
end

return M
