local M = {}

---@param config YorumiConfig
---@param theme YorumiTheme
function M.setup(config, theme)
  return {
    ColorColumn   = { bg = theme.ui.bg_p1 },
    Conceal       = { bg = theme.ui.bg_gutter },
    Cursor        = { bg = theme.ui.fg, fg = theme.ui.bg },
    lCursor       = { link = "Cursor" },
    CursorIM      = { link = "Cursor" },
    CursorColumn  = { bg = theme.ui.bg_p1 },
    CursorLine    = { link = "CursorColumn" },
    Directory     = { fg = theme.diag.info },
    DiffAdd       = { bg = theme.diff.add, fg = theme.vcs.added },
    DiffChange    = { bg = theme.diff.change, fg = theme.vcs.changed },
    DiffDelete    = { bg = theme.diff.delete, fg = theme.diag.error },
    DiffText      = { bg = theme.vcs.changed, fg = theme.ui.bg },
    EndOfBuffer   = { fg = theme.ui.nontext },
    ErrorMsg      = { fg = theme.diag.error },
    WinSeparator  = { fg = theme.ui.fg_gutter },
    VertSplit     = { link = "WinSeparator" },
    Folded        = { fg = theme.diag.hint, bg = theme.ui.bg_gutter },
    FoldColumn    = { bg = theme.ui.bg_gutter },
    SignColumn    = { bg = theme.ui.bg, fg = theme.ui.fg_gutter },
    Substitute    = { bg = theme.diff.add, fg = theme.vcs.added },
    LineNr        = { bg = theme.ui.bg, fg = theme.ui.nontext },
    CursorLineNr  = { fg = theme.ui.fg_dim },
    MatchParen    = { bg = theme.ui.bg_gutter, fg = theme.ui.fg_dim },
    ModeMsg       = { bg = theme.ui.bg_p1, bold = true },
    MsgArea       = vim.o.cmdheight == 0 and { link = "StatusLine" } or { fg = theme.ui.fg_dim },
    MsgSeparator  = { bg = vim.o.cmdheight == 0 and theme.ui.bg or theme.ui.bg_p1 },
    MoreMsg       = { fg = theme.diag.info },
    NonText       = { fg = theme.ui.nontext },
    Normal        = { bg = theme.ui.bg, fg = theme.ui.fg },
    NormalFloat   = { bg = theme.ui.float.bg, fg = theme.ui.fg },
    FloatBorder   = { bg = theme.ui.float.bg, fg = theme.ui.float.fg_border },
    FloatTitle    = { bg = theme.ui.float.bg, fg = theme.ui.fg_dim },
    FloatFooter   = { bg = theme.ui.float.bg, fg = theme.ui.fg_dim },
    NormalNC      = config.dimInactive and { bg = theme.ui.bg_p1, fg = theme.ui.fg_dim } or { link = "Normal" },
    Pmenu         = { bg = theme.ui.pmenu.bg, fg = theme.ui.pmenu.fg },
    PmenuSel      = { bg = theme.ui.pmenu.bg_sel, fg = theme.ui.pmenu.fg_sel },
    PmenuKind     = { bg = theme.ui.bg, fg = theme.ui.fg_dim },
    PmenuKindSel  = { bg = theme.ui.pmenu.bg_sel, fg = theme.ui.pmenu.fg_sel },
    PmenuExtra    = { bg = theme.ui.bg, fg = theme.ui.fg_dim },
    PmenuExtraSel = { bg = theme.ui.pmenu.bg_sel, fg = theme.ui.pmenu.fg_sel },
    PmenuSbar     = { bg = theme.ui.pmenu.bg_sbar },
    PmenuThumb    = { bg = theme.ui.pmenu.bg_thumb },
    Question      = { link = "MoreMsg" },
    QuickFixLine  = { bg = theme.ui.bg_gutter },
    CurSearch     = { bg = theme.ui.bg_CurSearch, fg = theme.ui.fg_CurSearch },
    IncSearch     = { bg = theme.ui.bg_search, fg = theme.ui.fg_search },
    Search        = { bg = theme.ui.bg_search, fg = theme.ui.fg_search },
    SpecialKey    = { fg = theme.diag.error },
    SpellBad      = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.error },
    SpellCap      = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.warning },
    SpellLocal    = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.warning },
    SpellRare     = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.warning },
    StatusLine    = { bg = theme.ui.bg_p2, fg = theme.ui.fg },
    StatusLineNC  = { bg = theme.ui.bg_p1, fg = theme.ui.fg },
    TabLine       = { bg = theme.ui.bg_gutter },
    TabLineFill   = { bg = theme.ui.bg },
    TabLineSel    = { bg = theme.ui.bg },
    Title         = { bg = theme.ui.bg_p1, fg = theme.diag.hint },
    Visual        = { bg = theme.ui.bg_visual, fg = theme.ui.fg_visual },
    VisualNOS     = { link = "Visual" },
    WarningMsg    = { fg = theme.diag.warning },
    Whitespace    = { fg = theme.ui.whitespace },
    WildMenu      = { link = "Pmenu" },
    WinBar        = { fg = theme.ui.fg_dim, bg = "NONE" },
    WinBarNC      = { fg = theme.ui.bg_gutter, bg = config.dimInactive and theme.ui.bg_p1 or "NONE" },

    debugPC       = { bg = theme.diag.error },
    -- debugBreakpoint = 

    LspReferenceText  = { fg = theme.ui.fg_dim },
    LspReferenceRead  = { link = "LspReferenceText" },
    LspReferenceWrite = { fg = theme.ui.fg_dim, underline = true },

    DiagnosticError = { fg = theme.diag.error },
    DiagnosticWarn  = { fg = theme.diag.warning },
    DiagnosticInfo  = { fg = theme.diag.info },
    DiagnosticHint  = { fg = theme.diag.info },
    DiagnosticOk    = { fg = theme.diag.ok },

    DiagnosticFloatingError = { fg = theme.diag.error },
    DiagnosticFloatingWarn  = { fg = theme.diag.warning },
    DiagnosticFloatingInfo  = { fg = theme.diag.info },
    DiagnosticFloatingHint  = { fg = theme.diag.info },
    DiagnosticFloatingOk    = { fg = theme.diag.ok },

    DiagnosticSignError = { fg = theme.diag.error },
    DiagnosticSignWarn  = { fg = theme.diag.warning },
    DiagnosticSignInfo  = { fg = theme.diag.info },
    DiagnosticSignHint  = { fg = theme.diag.info },
    DiagnosticSignOk    = { fg = theme.diag.ok },

    DiagnosticVirtualTextError = { link = "DiagnosticError" },
    DiagnosticVirtualTextWarn  = { link = "DiagnosticWarn" },
    DiagnosticVirtualTextInfo  = { link = "DiagnosticInfo" },
    DiagnosticVirtualTextHint  = { link = "DiagnosticHint" },

    DiagnosticUnderlineError = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.error },
    DiagnosticUnderlineWarn  = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.warning },
    DiagnosticUnderlineInfo  = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.info },
    DiagnosticUnderlineHint  = { undercurl = config.undercurl, underline = not config.undercurl, sp = theme.diag.info },

    LspSignatureActiveParameter = { fg = theme.diag.warning },
    LspCodeLens = { fg = theme.ui.fg_dim },

    diffAdded   = { fg = theme.vcs.added },
    diffRemoved = { fg = theme.diag.error },
    diffDeleted = { fg = theme.diag.error },
    diffChanged = { fg = theme.diag.warning },
    diffOldFile = { fg = theme.diag.error },
    diffNewFile = { fg = theme.diff.add },

    NvimInternalError = { bg = theme.diag.error_bg, fg = theme.diag.error }
  }
end

return M
